### ISSUE TITLE
Update is migrating tuples when it shouldn't

### ISSUE THREAD

**Issue by jrolli** [yash620/terrier#31]
I'm still validating my concurrent tests, but it looks like we have a logic bug somewhere in `SqlTable::Update` that is causing tuples to migrate when they shouldn't (version match).

Specifically, I am calling update and it is failing the assertion that the returned tuple slot should match the tuple slot passed when the schema matches or only has column deletions.

**Comment by yashNaN** [comment]
`
   auto old_pair = InitializerForProjectedRow(redo_col_oids, version_num);

    // 1. Create a ProjectedRow Buffer for the old version
    byte *buffer = common::AllocationUtil::AllocateAligned(old_pair.first.ProjectedRowSize());
    storage::ProjectedRow *pr = old_pair.first.InitializeRow(buffer);

    // 2. Copy from new ProjectedRow to old ProjectedRow
    StorageUtil::CopyProjectionIntoProjection(redo, map, tables_.Find(version_num)->second.layout, pr, old_pair.second);

    // 3. Update the old data-table
    bool result = tables_.Find(old_version)->second.data_table->Update(txn, slot, *pr);
    delete[] buffer;
    if (!result) {
      return {false, slot};
    }
    ret_slot = slot;`

This is code in update if the the update is not touching any new columns. I am a bit confused here. So on line 1 we get a projected row initializer for version_num. version_num is the version passed in, so that is the expected version. But on line 11 we use (*pr) in the update call and pr is the ProjectedRow from the initializer. So this ProjectedRow will be in the expected version, but we are passing it into the data_table update call for the actual version. Isn’t this an error? Data_table wouldn’t know how to handle something that is not of it’s version.

**Comment by jrolli** [comment]
This issue is fixed in the pending PR for concurrent tests (#33).
